/*
 * This Kotlin source file was generated by the Gradle "init" task.
 */
package jvm.roots.branches

import org.junit.jupiter.api.Test

import org.junit.jupiter.api.Assertions.*

class LinkedListTest {
    @Test fun testConstructor() {
        val list = LinkedList<Int>()
        assertEquals(0, list.size())
    }

    @Test fun testAdd() {
        val list = LinkedList<String>()

        list.add("one")
        assertEquals(1, list.size())
        assertEquals("one", list.get(0))

        list.add("two")
        assertEquals(2, list.size())
        assertEquals("two", list.get(1))
    }
}
