name: on_push

on:
    push:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Check github-action expressions
              run: echo "${{ join('["test", "test2"]', '-') }}"
            - name: Another expression test
              run: ls "${{ github.workspace }}"
